const $=s=>document.querySelector(s);let active='city',requested=false;
const worlds={city:{room:'Forest Villa 07',chat:'How can we help?',chatText:'Ask about your villa, dining or activities. For arrangements that need confirmation, I can prepare a request for the hotel team.',assistant:'Your Sanctuary concierge',questions:['What’s happening tomorrow?','Can we have breakfast on our terrace?','Can I book a spa treatment?'],event:'07:30 · Morning yoga',eventDetail:'The garden pavilion. Suitable for beginners; host confirms spaces.',event2:'16:00 · A walk through the village',eventDetail2:'Meet at reception. Guided, easy pace; subject to weather.',guide:'Breakfast is served 07:00–10:30. Check-in is from 15:00, and checkout is by 11:00. For terrace breakfast, please request a time with your host; availability and any charges need confirmation.',food:'Your host can suggest a village walk or private dining experience and confirm availability. I can prepare a request with your preferences.'}};
function reset(){requested=false;$('#messages').replaceChildren();$('#question').value='';const d=worlds[active];$('#chatWelcome').hidden=false;$('#chatWelcome').innerHTML=`<div class="greeting">${d.chat}</div><p>${d.chatText}</p><div class="chat-context"><i></i> ${d.room} · Your sample stay</div>${d.questions.map(q=>`<button class="suggestion" data-ask="${q}">${q}<span>↗</span></button>`).join('')}`;$('#chatContent').scrollTop=0}
function openChat(){$('#chat').hidden=false;$('#launch').hidden=true;$('#guide').hidden=true}
function ask(q){if(!q.trim())return;openChat();$('#chatWelcome').hidden=true;const d=worlds[active];const u=document.createElement('div');u.className='user-message';u.textContent=q;$('#messages').append(u);let text,source='Guest guide',action=false;if(/(?:pool|terrace).*breakfast|breakfast.*(?:pool|terrace)/i.test(q)){text='I can prepare a terrace breakfast request for your host, who will confirm a time, availability, and any charge. It is not booked automatically.';action=true}else if(/tomorrow|happening|schedule|event/i.test(q)){text=`For <strong>Saturday 26 September</strong>, here’s the sample programme:<div class="schedule"><strong>${d.event}</strong><p>${d.eventDetail}</p><strong>${d.event2}</strong><p>${d.eventDetail2}</p></div>Would you like me to prepare a request for the team?`;source='Activities calendar';action=true}else if(/late|book|sauna|help|broken|not working|room issue/i.test(q)){text=/late/i.test(q)?'Standard checkout is <strong>11 am</strong>. Late checkout depends on availability. I can prepare a request for reception, but it isn’t confirmed until the team responds.':'I can prepare a request for the team with your room and this conversation attached. The team will need to confirm availability or the next step.';action=true}else if(/eat|dinner|swim|walk|trail/i.test(q)){text=d.food;action=true}else if(/breakfast|check|arriv|wifi|wi-fi/i.test(q)){text=d.guide}else{text='This prototype can help with arrival, breakfast, tomorrow’s activities, and requests for the hotel team. For this question, I can prepare a request instead of guessing.';action=true}
const a=document.createElement('div');a.className='answer';a.innerHTML=`<div class="answer-name">${d.assistant}</div><div>${text}</div><button class="citation" ${source==='Activities calendar'?'data-calendar':'data-guide'}>↗ ${source}</button>${action?`<button class="request" ${requested?'disabled':''}>${requested?'Demo request prepared':'Request help from the team'}</button>`:''}`;$('#messages').append(a);$('#question').value='';$('#chatContent').scrollTop=$('#chatContent').scrollHeight;}
document.addEventListener('click',e=>{let b=e.target.closest('[data-theme]');if(b){render(b.dataset.theme);return}if(e.target.closest('[data-chat]'))openChat();b=e.target.closest('[data-ask]');if(b)ask(b.dataset.ask);if(e.target.closest('[data-guide]')){$('#guide').hidden=false;$('#chat').hidden=true;$('#launch').hidden=false}if(e.target.closest('#closeGuide'))$('#guide').hidden=true;if(e.target.closest('[data-calendar]')){$('#chat').hidden=true;$('#launch').hidden=false;$('#happenings').scrollIntoView({behavior:'smooth'})}b=e.target.closest('.request');if(b&&!requested){requested=true;b.disabled=true;b.textContent='✓ Demo request prepared';const note=document.createElement('p');note.className='request-note';note.textContent='Request G-1042 includes your room and conversation. Nothing has been sent or booked.';b.after(note);$('#chatContent').scrollTop=$('#chatContent').scrollHeight;}});$('#closeChat').onclick=()=>{$('#chat').hidden=true;$('#launch').hidden=false};$('#reset').onclick=reset;$('#chatForm').onsubmit=e=>{e.preventDefault();ask($('#question').value)};reset();$('#chat').hidden=true;

const villaData=[{title:'The Forest<br>Suite',meta:'ONE BEDROOM · TWO GUESTS · PRIVATE POOL',image:'assets/suite.png',description:'A one-bedroom villa for two guests, with natural linen, a private pool and forest views.'},{title:'Private Pool<br>Terrace',meta:'FOREST VIEWS · PRIVATE POOL · SHADED DAYBEDS',image:'assets/forest-pool.png',description:'Your private terrace has an infinity pool and shaded daybeds overlooking the forest.'},{title:'Terrace<br>Breakfast',meta:'TERRACE SERVICE · REQUEST WITH YOUR HOST',image:'assets/breakfast.png',description:'Fresh fruit, warm pastries, and coffee on your terrace. Ask your host to arrange a breakfast time; availability and any charges require confirmation.'}];let villaIndex=0;function villaStep(n){villaIndex=(villaIndex+n+villaData.length)%villaData.length;const v=villaData[villaIndex];$('#villaImage').src=v.image;$('#villaImage').alt=v.title.replace('<br>',' ');$('#villaTitle').innerHTML=v.title;$('#villaMeta').textContent=v.meta;$('#villaDescription').textContent=v.description;$('#villaNumber').textContent='0'+(villaIndex+1)+' / 03';}$('#previousVilla').onclick=()=>villaStep(-1);$('#nextVilla').onclick=()=>villaStep(1);
$('#menuButton').onclick=()=>{const opened=$('#menu').hidden;$('#menu').hidden=!opened;$('#menuButton').setAttribute('aria-expanded',String(opened));$('#menuButton').setAttribute('aria-label',opened?'Close navigation':'Open navigation');document.body.classList.toggle('menu-open',opened)};$('#menu').onclick=e=>{if(e.target.closest('a,button')){$('#menu').hidden=true;document.body.classList.remove('menu-open');$('#menuButton').setAttribute('aria-expanded','false');$('#menuButton').setAttribute('aria-label','Open navigation')}};

// Keep the still image for visitors who prefer reduced motion.
const heroVideo = $('#heroVideo');
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
async function playHero() {
  if (!heroVideo.getAttribute('src')) heroVideo.src = 'assets/hero-rotation.mp4';
  heroVideo.muted = true;
  try { await heroVideo.play(); } catch { /* Keep the poster if autoplay is blocked. */ }
}
heroVideo.addEventListener('error', () => { heroVideo.hidden = true; });
reducedMotion.addEventListener('change', event => {
  if (event.matches) heroVideo.pause();
  else playHero();
});
if (!reducedMotion.matches) playHero();
